version: '3'
services:
  nats-server:
    image: nats:2.11
    container_name: nats
    command: ["-js"]

  contacts:
    build: ./cmd/gochat-contacts_server
    container_name: gochat-contacts_server
    environment:
      - NATS_URL=nats://nats-server:4222
      - S3_ENDPOINT=http://bucket:9000
    depends_on:
      - nats-server
  auth:
    build: ./cmd/gochat-auth_server
    container_name: gochat-auth_server
    environment:
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
  chatcmd:
    build: ./cmd/gochat-chatcmd_server
    container_name: gochat-chatcmd_server
    environment:
      - DB_URL=chatview-db:6379
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - chatview-db
      - nats-server
  chatview:
    build: ./cmd/gochat-chatview_server
    container_name: gochat-chatview_server
    environment:
      - DB_URL=chatview-db:6379
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
      - chatview-db
  messages:
    build: ./cmd/gochat-message_server
    container_name: gochat-message_server
    environment:
      - CONTACTS_SERVER=contacts:8080
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
  ws:
    build: ./cmd/ws-server
    container_name: ws-server
    environment:
      - AUTH_SERVER=auth:8080
      - CONTACTS_SERVER=contacts:8080
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
      - auth
      - contacts
  bucket:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/data", "--console-address", ":9001"]

  krakend:
    image: krakend:2.10
    container_name: krakend
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8080:8080"
    command: ["run", "-c", "/etc/krakend/krakend.json", "-d"]


  chatview-db:
    image: redis:8.2
    container_name: chatview-db
  
