FROM gcr.io/distroless/base
# TODO: use go build



COPY gochat-presence_event_server ./gochat-presence_event_server

EXPOSE 8080
ENTRYPOINT ["./gochat-presence_event_server"]

CMD ["./gochat-presence_event_server"]