package domain
package domain























































}	LastUsedAt time.Time `json:"last_used_at"`	CreatedAt  time.Time `json:"created_at"`	UserId     int32     `json:"user_id"`	KeyName    string    `json:"key_name"`	Id         int32     `json:"id"`type Passkey struct {}	return int32(id), nil	}		return 0, err	if err != nil {	id, err := strconv.ParseInt(string(userHandle), 10, 32)func UserIdFromUserHandler(userHandle []byte) (int32, error) {}	return []byte(strconv.FormatInt(int64(userId), 10))func UserHandlerIdBytes(userId int32) []byte {}	return u.Credentialsfunc (u *WebAuthnUser) WebAuthnCredentials() []webauthn.Credential {}	return u.Iconfunc (u *WebAuthnUser) WebAuthnIcon() string {}	return u.DisplayNamefunc (u *WebAuthnUser) WebAuthnDisplayName() string {}	return u.Namefunc (u *WebAuthnUser) WebAuthnName() string {}	return UserHandlerIdBytes(u.Id)func (u *WebAuthnUser) WebAuthnID() []byte {}	Credentials []webauthn.Credential	Icon        string	DisplayName string	Name        string	Id          int32type WebAuthnUser struct {)	"github.com/go-webauthn/webauthn/webauthn"	"time"	"strconv"import (